### PR TITLE
Modify schema

### PR DESCRIPTION
**Pull request by ka-sarthak**
- Modifies schema: PolymerizationReaction is to be used for one reaction
  - add publication_reference subsection; make PolymerizationReaction an Activity
  - add Monomer sub-section and define it's class Monomer
  - add Polymer sub-section
  - use PubChemPureSubstanceSection for solvent
  - make reaction_condition non-repeated. 
- Add a util method to convert JSON from llm to `archive.yaml` that uses `m_def=PolymerizationReaction`
- Add test and test data for schema and utils

### CODE REVIEW

**Review by Pepe-Marquez — COMMENTED** [review]
LGTM. 

Change in the app the path for solvent (in the two places in columns), before was a Quantity and now it becomes a subsection.

Then let's merge, and if we dump the data and gets picked by the app when can deploy in the example Oasis and keep on improving there.

**Comment by Pepe-Marquez** [comment]
Once it is deployed, you can add the files in an upload and get me, @kjappelbaum, and @marawilhelmi as co-authors, so we can see the entries and then comment on how to improve. I keep further communication in discord.

**Comment by ka-sarthak** [comment]
@Pepe-Marquez I have fixed the solvents' path in the app's columns. However, there's another error in the app that is unrelated to this PR. The order_by in pagination is based on solvent, resulting in `is not a doc quantity` error. I am commenting it out.

**Comment by Pepe-Marquez** [comment]
Perfect. Merge, deploy in the test oasis and let's dump some entries! 👏

**Pull request merged**
